exports.methodError = 'METHOD_NOT_SUPPORTED';
exports.otpMessage = 'OTP_SEND_SUCCESSFULLY';
exports.changeMessage = 'PASSWORD_CHANGED_SUCCESSFULLY';
exports.resetMessage = 'PASSWORD_RESET_SUCCESSFULLY';
exports.userError = 'USER_NOT_FOUND';
exports.userExists = 'USER_ALREADY_EXISTS';
exports.logOutMessage = 'LOGOUT_SUCCESSFULLY';
exports.passwordError = 'PASSWORD_MISMATCH';
exports.compareOldPassword = 'OLD_PASSWORD_DID_NOT_MATCH';
exports.emailValidationError = 'INVAILD_EMAIL';
exports.phoneValidationError = 'INVALID_PHONE';
exports.userRegistrationMessage = 'YOUR_REQUEST_HAS_BEEN_SUBMITTED_SUCCESSFULLY';
exports.alreadySubmittReqMessage = 'YOUR_REQUEST_IS_STILL_PENDING';
exports.productError = 'PRODUCT_NOT_FOUND';
exports.otpMisMatch = 'OTP_DID_NOT_MATCH';
exports.otpExpires = 'INVALID_OTP_OR_OTP_EXPIRED';
exports.noMore='enable_to_add_more_question';
exports.users = [
  {
    type: "admin",
    status: "active",
    firstName: "nena",
    lastName: "Sharma",
    userName: "nena",
    email: "nena@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7304256, 29.0442524], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "hindi", name: "english" }],
    ethnicity: "indian",
    bodyType: "slim",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "aries",

    alcohol: "occasionally",
    smoking: "never",
    marijuana: "never",
    diet: "veg",
    pets: "like",
    maritalStatus: "yes",
    wantsKids: "no",
    age: 23,
    phone: "11",
    occcupation: "developer",
    height: 300,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes yes",
    basicQuestions: [
      {
        questionId: "5f3fc379cfa76a07a461f6ce",
        que:'giiiii',
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        questionId: "5f3fc383cfa76a07a461f6d1",
        que:'giiiii',
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        questionId: "5f3fc389cfa76a07a461f6d4",
        que:'giiiii',
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 20, to: 25 },
      height: { from: 100, to: 200},
      orientation: "male",
      distance: 54,
      bodyType: "fit",
      languages: [{ name: "hindi", name: "english" }],
      entnicity: "asia",
      religion: "hinduism",
      pets: "like",
      maritalStatus: "yes",
      wantsKids: "no",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "veg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "reena",
    lastName: "Sharma",
    userName: "reena",
    email: "reena@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.729408022016, 29.042476216210893], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "english" }],
    ethnicity: "africa",
    bodyType: "fit",
    politics: "notInterested",
    employment: "yes",
    astrologicalSign: "taurus",
    alcohol: "occasionally",
    smoking: "never",
    marijuana: "occasionally",
    diet: "nonVeg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "yes",
    age: 25,
    phone: "22",
    occcupation: "designer",
    height: 500,
    religion: "christianity",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 2",
          _id: "5f3fc379cfa76a07a461f6d0",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 24, to: 28 },
      height: { from: 300, to: 600 },
      orientation: "male",
      distance: 84,
      bodyType: "fit",
      languages: [{ name: "hindi", name: "english" }],
      entnicity: "africa",
      religion: "christianity",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "no",
      astrologicalSign: "taurus",
      alcohol: "never",
      smoking: "never",
      diet: "nonVeg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "rohan",
    lastName: "Sharma",
    userName: "rohan",
    email: "rohan@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.727866757661, 29.039493120052484], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "hindi", name: "english" }],
    ethnicity: "africa",
    bodyType: "fit",
    politics: "interested",
    employment: "no",
    astrologicalSign: "aries",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "always",
    diet: "veg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 20,
    phone: "33",
    occcupation: "painter",
    height: 700,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 18, to: 30 },
      height: { from: 500, to: 600 },
      orientation: "female",
      distance: 14,
      bodyType: "slim",
      languages: [{ name: "hindi" }],
      entnicity: "indian",
      religion: "christianity",
      pets: "like",
      maritalStatus: "no",
      wantsKids: "no",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "veg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "ritivik",
    lastName: "Sharma",
    userName: "ritivik",
    email: "ritivik@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.728786420077, 29.043808152370595], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "chinese", name: "english" }],
    ethnicity: "indian",
    bodyType: "fit",
    politics: "notInterested",
    employment: "no",
    astrologicalSign: "gemini",
    alcohol: "never",
    smoking: "never",
    marijuana: "never",
    diet: "veg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 30,
    phone: "44",
    occcupation: "singer",
    height: 600,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 1",
          _id: "5f3fc383cfa76a07a461f6d2",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 2",
          _id: "5f3fc389cfa76a07a461f6d6",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 25, to: 30 },
      height: { from: 200, to: 300 },
      orientation: "female",
      distance: 30,
      bodyType: "fit",
      languages: [{ name: "chinese", name: "english" }],
      entnicity: "asia",
      religion: "hinduism",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "never",
      smoking: "never",
      diet: "veg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "reema",
    lastName: "Sharma",
    userName: "reema",
    email: "reema@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.727181117981, 29.053967471641922], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "english" }],
    ethnicity: "africa",
    bodyType: "slim",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "gemini",
    alcohol: "never",
    smoking: "never",
    marijuana: "never",
    diet: "nonVeg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 20,
    phone: "55",
    occcupation: "singer",
    height: 500,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        questionNo: 2,
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        questionNo: 3,
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 26, to: 28 },
      height: { from: 300, to: 500 },
      orientation: "male",
      distance: 30,
      bodyType: "slim",
      languages: [{ name: "hindi", name: "english" }],
      entnicity: "africa",
      religion: "hinduism",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "never",
      smoking: "never",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "pawan",
    lastName: "Sharma",
    userName: "pawan",
    email: "pawan@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7293657772243, 29.05714212896121], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "chinese", name: "english" }],
    ethnicity: "africa",
    bodyType: "skinny",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "cancer",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "occasionally",
    diet: "nonVeg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 30,
    phone: "66",
    occcupation: "painter",
    height: 600,
    religion: "islam",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 22, to: 24 },
      height: { from: 600, to: 800 },
      orientation: "female",
      distance: 60,
      bodyType: "skinny",
      languages: [{ name: "spanish", name: "english" }],
      entnicity: "europe",
      religion: "islam",
      pets: "like",
      maritalStatus: "no",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "cancer",
      alcohol: "occasionally",
      smoking: "occasionally",
      diet: "veg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "seeta",
    lastName: "Sharma",
    userName: "seeta",
    email: "seeta@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7266205362975, 29.06744568381427], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "spanish", name: "english" }],
    ethnicity: "europe",
    bodyType: "skinny",
    politics: "notInterested",
    employment: "yes",
    astrologicalSign: "cancer",
    alcohol: "occasionally",
    smoking: "never",
    marijuana: "never",
    diet: "nonVeg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 25,
    phone: "77",
    occcupation: "designer",
    height: 500,
    religion: "islam",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 2",
          _id: "5f3fc389cfa76a07a461f6d6",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 20, to: 30 },
      height: { from: 400, to: 600 },
      orientation: "male",
      distance: 50,
      bodyType: "skinny",
      languages: [{ name: "english" }],
      entnicity: "europe",
      religion: "islam",
      pets: "dislike",
      maritalStatus: "no",
      wantsKids: "no",
      employment: "no",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "retesh",
    lastName: "Sharma",
    userName: "retesh",
    email: "retesh@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7245622761547, 29.09395705463578], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "chinese" }],
    ethnicity: "europe",
    bodyType: "slim",
    politics: "interested",
    employment: "no",
    astrologicalSign: "leo",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "never",
    diet: "veg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 27,
    phone: "88",
    occcupation: "developer",
    height: 600,
    religion: "buddhism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 21, to: 27 },
      height: { from: 500, to: 700 },
      orientation: "female",
      distance: 50,
      bodyType: "fit",
      languages: [{ name: "chinese" }],
      entnicity: "indian",
      religion: "hinduism",
      pets: "like",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "cancer",
      alcohol: "occasionally",
      smoking: "occasionally",
      diet: "veg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },

  {
    type: "user",
    status: "active",
    firstName: "mehar",
    lastName: "Sharma",
    userName: "mehar",
    email: "mehar@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7304256, 29.0442524], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "hindi" }],
    ethnicity: "indian",
    bodyType: "slim",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "aries",

    alcohol: "occasionally",
    smoking: "never",
    marijuana: "never",
    diet: "nonVeg",
    pets: "like",
    maritalStatus: "yes",
    wantsKids: "no",
    age: 23,
    phone: "123",
    occcupation: "developer",
    height: 600,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 26, to: 27 },
      height: { from: 800, to: 900 },
      orientation: "male",
      distance: 54,
      bodyType: "fit",
      languages: [{ name: "hindi" }],
      entnicity: "asia",
      religion: "hinduism",
      pets: "like",
      maritalStatus: "yes",
      wantsKids: "no",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "jahar",
    lastName: "Sharma",
    userName: "jahar",
    email: "jahar@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.729408022016, 29.042476216210893], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "english" }],
    ethnicity: "africa",
    bodyType: "fit",
    politics: "notInterested",
    employment: "yes",
    astrologicalSign: "taurus",
    alcohol: "occasionally",
    smoking: "never",
    marijuana: "occasionally",
    diet: "veg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "yes",
    age: 25,
    phone: "234",
    occcupation: "designer",
    height: 500,
    religion: "christianity",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 2",
          _id: "5f3fc379cfa76a07a461f6d0",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 30, to: 22 },
      height: { from: 500, to: 600 },
      orientation: "male",
      distance: 84,
      bodyType: "fit",
      languages: [{ name: "english" }],
      entnicity: "africa",
      religion: "christianity",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "no",
      astrologicalSign: "taurus",
      alcohol: "never",
      smoking: "never",
      diet: "veg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "raghav",
    lastName: "Sharma",
    userName: "raghav",
    email: "raghav@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.727866757661, 29.039493120052484], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "english" }],
    ethnicity: "africa",
    bodyType: "fit",
    politics: "interested",
    employment: "no",
    astrologicalSign: "aries",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "always",
    diet: "veg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 20,
    phone: "345",
    occcupation: "painter",
    height: 700,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 28, to: 30},
      height: { from: 600, to: 700 },
      orientation: "female",
      distance: 14,
      bodyType: "slim",
      languages: [{ name: "hindi" }],
      entnicity: "indian",
      religion: "christianity",
      pets: "like",
      maritalStatus: "no",
      wantsKids: "no",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "veg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "rishi",
    lastName: "Sharma",
    userName: "rishi",
    email: "rishi@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.728786420077, 29.043808152370595], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "chinese" }],
    ethnicity: "indian",
    bodyType: "fit",
    politics: "notInterested",
    employment: "no",
    astrologicalSign: "gemini",
    alcohol: "never",
    smoking: "never",
    marijuana: "never",
    diet: "nonVeg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 30,
    phone: "456",
    occcupation: "singer",
    height: 650,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 1",
          _id: "5f3fc383cfa76a07a461f6d2",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 2",
          _id: "5f3fc389cfa76a07a461f6d6",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 29, to: 32 },
      height: { from: 400, to: 600 },
      orientation: "female",
      distance: 30,
      bodyType: "fit",
      languages: [{ name: "english" }],
      entnicity: "asia",
      religion: "hinduism",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "never",
      smoking: "never",
      diet: "nonVeg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "reha",
    lastName: "Sharma",
    userName: "reha",
    email: "reha@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.727181117981, 29.053967471641922], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "english" }],
    ethnicity: "africa",
    bodyType: "slim",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "gemini",
    alcohol: "never",
    smoking: "never",
    marijuana: "never",
    diet: "nonVeg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 20,
    phone: "789",
    occcupation: "singer",
    height: 500,
    religion: "hinduism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 30, to: 33 },
      height: { from: 300, to: 400 },
      orientation: "male",
      distance: 30,
      bodyType: "slim",
      languages: [{ name: "english" }],
      entnicity: "africa",
      religion: "hinduism",
      pets: "dislike",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "gemini",
      alcohol: "never",
      smoking: "never",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "rehan",
    lastName: "Sharma",
    userName: "rehan",
    email: "rehan@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7293657772243, 29.05714212896121], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "english" }, { name: "chinese" }],
    ethnicity: "africa",
    bodyType: "skinny",
    politics: "interested",
    employment: "yes",
    astrologicalSign: "cancer",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "occasionally",
    diet: "veg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 30,
    phone: "134",
    occcupation: "painter",
    height: 600,
    religion: "islam",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "yes",
      men: "no",
      age: { from: 20, to: 23 },
      height: { from: 200, to: 400 },
      orientation: "female",
      distance: 60,
      bodyType: "skinny",
      languages: [{ name: "english" }, { name: "spanish" }],
      entnicity: "europe",
      religion: "islam",
      pets: "like",
      maritalStatus: "no",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "cancer",
      alcohol: "occasionally",
      smoking: "occasionally",
      diet: "veg",
      politics: "notInterested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "nidhi",
    lastName: "Sharma",
    userName: "nidhi",
    email: "nidhi@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7266205362975, 29.06744568381427], // [<longitude>, <latitude>]
      },
    },
    gender: "female",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "female",
    languages: [{ name: "english" }, { name: "spanish" }],
    ethnicity: "europe",
    bodyType: "skinny",
    politics: "notInterested",
    employment: "yes",
    astrologicalSign: "cancer",
    alcohol: "occasionally",
    smoking: "never",
    marijuana: "never",
    diet: "veg",
    pets: "dislike",
    maritalStatus: "yes",
    wantsKids: "yes",
    age: 25,
    phone: "3245",
    occcupation: "designer",
    height: 500,
    religion: "islam",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "yes",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 2",
          _id: "5f3fc389cfa76a07a461f6d6",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 23, to: 26 },
      height: { from: 600, to: 800 },
      orientation: "male",
      distance: 50,
      bodyType: "skinny",
      languages: [{ name: "english" }],
      entnicity: "europe",
      religion: "islam",
      pets: "dislike",
      maritalStatus: "no",
      wantsKids: "no",
      employment: "no",
      astrologicalSign: "gemini",
      alcohol: "occasionally",
      smoking: "never",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
  {
    type: "user",
    status: "active",
    firstName: "rihaan",
    lastName: "Sharma",
    userName: "rihaan",
    email: "rihaan@gmail.com",
    isExists: "true",
    address: {
      line: "hisar haryana",
      postalCode: "125001",
      city: "hisar",
      landmark: "hisar",
      location: {
        type: "Point",
        coordinates: [75.7245622761547, 29.09395705463578], // [<longitude>, <latitude>]
      },
    },
    gender: "male",
    visibleName: "true",
    visibleAge: "true",
    visiblelikeDislike: "true",
    visibleImage: "true",
    visibleLocation: "true",

    orientation: "male",
    languages: [{ name: "english" }, { name: "chinese" }],
    ethnicity: "europe",
    bodyType: "slim",
    politics: "interested",
    employment: "no",
    astrologicalSign: "leo",
    alcohol: "occasionally",
    smoking: "occasionally",
    marijuana: "never",
    diet: "nonVeg",
    pets: "like",
    maritalStatus: "no",
    wantsKids: "no",
    age: 27,
    phone: "098",
    occcupation: "developer",
    height: 300,
    religion: "buddhism",
    images: [
      {
        url: String,
        thumbnail: String,
        resize_url: String,
        resize_thumbnail: String,
      },
    ],
    race: "no",
    basicQuestions: [
      {
        que:'giiiii',
        questionId: "5f3fc379cfa76a07a461f6ce",
        ans: {
          value: "option 1",
          _id: "5f3fc379cfa76a07a461f6cf",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc383cfa76a07a461f6d1",
        ans: {
          value: "option 2",
          _id: "5f3fc383cfa76a07a461f6d3",
        },
      },
      {
        que:'giiiii',
        questionId: "5f3fc389cfa76a07a461f6d4",
        ans: {
          value: "option 1",
          _id: "5f3fc389cfa76a07a461f6d5",
        },
      },
    ],
    aboutMeQuestions: [],
    interests: [],
    preferences: {
      women: "no",
      men: "yes",
      age: { from: 24, to: 30 },
      height: { from: 700, to: 900 },
      orientation: "female",
      distance: 50,
      bodyType: "fit",
      languages: [{ name: "english" }, { name: "chinese" }],
      entnicity: "indian",
      religion: "hinduism",
      pets: "like",
      maritalStatus: "yes",
      wantsKids: "yes",
      employment: "yes",
      astrologicalSign: "cancer",
      alcohol: "occasionally",
      smoking: "occasionally",
      diet: "nonVeg",
      politics: "interested",
    },
    loginType: "app",
    password: "$2b$10$GJJCSJrSxD1qSBisjp9mPu6fmRvEnmhTxhT0zYzML0PTOojkR4NSm",
  },
];
